# OSM data download pipeline

name: osm-download

variables:
  imageName: 'polygon-export-docker'

trigger:
# - master
- none

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: download
  strategy:
    matrix:
      #TODO: populate matrix config programatically
      #TODO: share matrix between pipelines
      obb:
        OSM_REGION: 'oberbayern'
        PBF_URL: 'http://download.geofabrik.de/europe/germany/bayern/oberbayern-latest.osm.pbf'
      de:
        OSM_REGION: 'germany'
        PBF_URL: 'https://download.geofabrik.de/europe/germany-latest.osm.pbf'
  steps:
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        wget --no-verbose --output-document=$(OSM_REGION).osm.pbf $(PBF_URL)

  - task: PublishBuildArtifacts@1
    enabled: true
    inputs:
      PathtoPublish: '$(OSM_REGION).osm.pbf'
      ArtifactName: 'osm-data'
      publishLocation: 'Container'
