# OSM polygon export pipeline
# Exports polygons of localities to geoJSON streams.
# https://aka.ms/yaml

name: polygon-pipeline

variables:
  imageName: 'polygon-export-docker'

trigger:
# - master
- none

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: prepare
  condition: false
  #TODO: build container for later jobs
  steps:
  - script: |
      set -x
      docker build -t polygon-export-docker:latest -<<EOF
      FROM ubuntu:18.04
      RUN apt-get update && apt-get install -y osmium-tool
      EOF

- job: export
  container: 
    image: krizleebear/docker-osmium-tool
    endpoint: docker-krizleebear

  strategy:
    matrix:
      #TODO: populate matrix config programatically
      algeria:
        OSM_REGION: 'algeria'
        PBF_URL: 'https://download.geofabrik.de/africa/algeria-latest.osm.pbf'
      angola:
        OSM_REGION: 'angola'
        PBF_URL: 'https://download.geofabrik.de/africa/angola-latest.osm.pbf'
        
  steps:
  - script: |
      set -x
      echo Install osmium
      sudo apt-get update
      sudo apt install -y osmium-tool
      osmium --version
    enabled: false

  - task: DownloadBuildArtifacts@0
    inputs:
      buildType: 'specific'
      project: 'f85b0393-1484-487a-b6d1-5120b54a70be'
      pipeline: '3'
      buildVersionToDownload: 'latest'
      downloadType: 'specific'
      itemPattern: '**/$(OSM_REGION).osm.pbf'
      downloadPath: '$(System.DefaultWorkingDirectory)'

#TODO: use this job instead, as changed in OSM-download pipeline already.
  - task: DownloadPipelineArtifact@2
    enabled: false
    inputs:
      buildType: 'current'
      targetPath: '$(Pipeline.Workspace)'

  - task: Bash@3
    displayName: 'filter and export polygons'
    inputs:
      targetType: 'inline'
      script: |
        set -x
        ls -la
        pwd
        osmium --version

        INPUT_PBF=osm-data/$(OSM_REGION).osm.pbf
        ADMIN_PBF=$(OSM_REGION).admins.pbf
        POLYGON_JSON=$(OSM_REGION).admin-polygons.geojsonseq

        osmium tags-filter --output ${ADMIN_PBF} --overwrite ${INPUT_PBF} boundary=administrative
        osmium export ${ADMIN_PBF} --output=${POLYGON_JSON} --omit-rs --overwrite #--geometry-types=polygon

  # TODO: remove deprecated job
  - task: PublishBuildArtifacts@1
    enabled: false
    inputs:
      PathtoPublish: '$(OSM_REGION).admin-polygons.geojsonseq'
      ArtifactName: 'polygons'
      publishLocation: 'Container'

  - task: PublishPipelineArtifact@1
    enabled: true
    displayName: 'Store polygon artifacts'
    inputs:
      targetPath: '$(OSM_REGION).admin-polygons.geojsonseq'
      artifact: 'admin-polygons-$(OSM_REGION)'
      publishLocation: 'pipeline'
