# OSM polygon export pipeline
# Exports polygons of localities to geoJSON streams.
# https://aka.ms/yaml

name: polygon-pipeline

variables:
  imageName: 'polygon-export-docker'

trigger:
# - master
- none

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: prepare
  #TODO: build container for later jobs




- job: export
  strategy:
    matrix:
      #TODO: populate matrix config programatically
      obb:
        OSM_REGION: 'oberbayern'
        PBF_URL: 'http://download.geofabrik.de/europe/germany/bayern/oberbayern-latest.osm.pbf'
      de:
        OSM_REGION: 'germany'
        PBF_URL: 'https://download.geofabrik.de/europe/germany-latest.osm.pbf'
  steps:
  - script: |
      echo Install osmium
      sudo apt-get update
      sudo apt install -y osmium-tool
      osmium --version

  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        # Write your commands here
        pwd
        echo $(PBF_URL)
        osmium --version
        #TODO: call the real scripts
        # the empty files are only place holders to test publishing
        #touch $(OSM_REGION).admin-polygons.geojsonseq

        INPUT_PBF=$(OSM_REGION).osm.pbf
        ADMIN_PBF=$(OSM_REGION).admins.pbf
        POLYGON_JSON=$(OSM_REGION).admin-polygons.geojsonseq

        wget --output-document=$(OSM_REGION).osm.pbf $(PBF_URL)
        osmium tags-filter --output ${ADMIN_PBF} --overwrite ${INPUT_PBF} boundary=administrative
        osmium export ${ADMIN_PBF} --output=${POLYGON_JSON} --omit-rs --overwrite #--geometry-types=polygon

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(OSM_REGION).admin-polygons.geojsonseq'
      ArtifactName: 'polygons'
      publishLocation: 'Container'
